[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(name)s: %(message)s
log_cli_date_format = %H:%M:%S
markers =
    local_runner
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
