[parameters]
[parameters.general]
# the package simstack.toml sets no db_name or connection string, the environment decides what is needed
[parameters.db]
database="test_db"
[resources]
allowed_resources=["self","local"]
[resources.local]
workdir="$HOME/simstack"
python_path=["$PROJECT"]
ssh_key="$HOME/.ssh/id_rsa"
hostname="test_hostname"
[routes]
self = []
local = ["self"]
[paths]
[paths.tests]
path = "tests"
drops = ""
use_pickle = false
# here we need to specify models and methods
[paths.models]
path = "src/simstack/models"
drops = "src"
use_pickle = false
[paths.methods]
path = "src/simstack/methods"
drops = "src"
use_pickle = false
