name: "Build Conda Package"
on:
  workflow_dispatch:
jobs:
  build_conda_package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install Conda Build
        run: conda install -c conda-forge conda-build

      - name: Build
        id: build
        run: |
          mkdir -p build/
          conda build conda-recipe/ --output-folder build/ --no-anaconda-upload
          OUTPUTFILE=$(conda build conda-recipe/ --output --output-folder build/ --no-anaconda-upload)
          echo "releasepath=$(realpath $OUTPUTFILE)" >> $GITHUB_OUTPUT

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: condapackage
          path: ${{ steps.build.outputs.releasepath }}
